### ISSUE TITLE
Add a generated identifier for faux part in Title 40

### ISSUE THREAD

**Issue by peregrinator** [criticaljuncture/ecfr-xml-corrections#103]
Title 40 Chapter V has an html table of contents, Index to Parts 1500 Through 1508, as a separate part between parts 1508 and 1515. This isn't actually a part and thus has no identifier. OFR would like us to display it and track changes for the purposes of the eCFR so we'll want to generate and random `ECFRXXXX` type identifier for it in a patch.

**Comment by barefootford** [comment]
It looks like this was already fixed/merged in June 25:
https://github.com/criticaljuncture/ecfr-xml-corrections/commit/2aee4639edfbb7cde31e9f02a279f41df9526ffb
