### ISSUE TITLE
Title 49 Amendment dates in future

### ISSUE THREAD

**Issue by peregrinator** [criticaljuncture/ecfr-xml-corrections#11]
Looks to be 2 separate patches here:

- TitleVersionPreprocessor::AmendmentDateExtractor::FutureAmendmentDate: 2018-03-30 is after 2017-04-05 for TitleVersion id: 566
- TitleVersionPreprocessor::AmendmentDateExtractor::FutureAmendmentDate: 2018-03-30 is after 2017-04-11 for TitleVersion id: 595
- TitleVersionPreprocessor::AmendmentDateExtractor::FutureAmendmentDate: 2018-03-30 is after 2017-04-14 for TitleVersion id: 610

and

- TitleVersionPreprocessor::AmendmentDateExtractor::FutureAmendmentDate: 2018-04-14 is after 2017-04-18 for TitleVersion id: 619

**Comment by barefootford** [comment]
In good news, our patch coverage % is getting much higher:
Already patched:
https://github.com/criticaljuncture/ecfr-xml-corrections/issues/7 https://github.com/criticaljuncture/ecfr-xml-corrections/pull/10/commits/30661480801b7b31d5c6237d5529b89f2c40b77d
