### ISSUE TITLE
Title 12 Amendment dates in future

### ISSUE THREAD

**Issue by peregrinator** [criticaljuncture/ecfr-xml-corrections#12]
- TitleVersionPreprocessor::AmendmentDateExtractor::FutureAmendmentDate: 242017-03-01 is after 2017-03-28 for TitleVersion id: 520
~~- TitleVersionPreprocessor::AmendmentDateExtractor::FutureAmendmentDate: 242017-03-01 is after 2017-03-28 for TitleVersion id: 520~~ This is the same error as above -af

**Comment by barefootford** [comment]
Looks like the same story for this one, already patched but didn't run:
https://github.com/criticaljuncture/ecfr-xml-corrections/blob/master/12/001-amddate/001.patch
