### ISSUE TITLE
Patch Title 32 AMDDATE year

### ISSUE THREAD

**Issue by barefootford** [criticaljuncture/ecfr-xml-corrections#128]
## Title 32 - Volume 2

Title 32 received_on `2019-03-11` through `2019-03-20`
have two amendment dates for  that are reverse from the `2019-03-08` amendment dates 

I'm not sure what was desired here so we'll probably need to talk to OFR to figure this out. 

<img width="716" alt="Screen Shot 2019-07-29 at 5 43 09 PM" src="https://user-images.githubusercontent.com/3782822/62092053-a64cd580-b228-11e9-82e4-9a2e2782ace3.png">

**Comment by peregrinator** [comment]
- It appears that the amendment in Vol 2 on 2019-03-05 should have been Feb 15, 2019 - in vol 2 it is only inserting XREF tags to a document that is effective on 02/15/2019
- No changes other than amendment dates from 2019-03-08 to 2019-03-11 -- 2019-03-11 looks to have been correcting the amendment date for vol2 to be Feb 15th 
 - [x] so we can remove the title version for 2019-03-11, and patch the previous couple (2019-03-05 until 2019-03-08)
- Changes in 2019-03-12 only affect volume 1 (not vol 2)
- Changes in 2019-03-13 only affect volume 2
  - removes part 337 - correct effective date
