### ISSUE TITLE
Title 37 amendment dates in future

### ISSUE THREAD

**Issue by peregrinator** [criticaljuncture/ecfr-xml-corrections#13]
- TitleVersionPreprocessor::AmendmentDateExtractor::FutureAmendmentDate: 2018-01-01 is after 2017-01-07 for TitleVersion id: 232

**Comment by barefootford** [comment]
I might need a second set of eyes @peregrinator, but I believe this is the same issue that was fixed here. I thought this was merged in before the last import though, but it appears the last time this Honeybadgered was 4 days ago:
https://github.com/criticaljuncture/ecfr-xml-corrections/pull/4/files
https://app.honeybadger.io/projects/51157/faults/34962428/af0ec504-2f1e-11e8-8eca-0d1cc0d23586#notice-summary

**Comment by peregrinator** [comment]
Ok this may have been related to the ecf-xml-corrections going missing on the server, I'll close for now and we can revisit - it was showing in the sidekiq log from 1 day ago...

**Comment by barefootford** [comment]
Yeah, if all the corrections were missing that would make perfect sense. Though... that also means we're going to be missing all of the recent patches with the latest import. :-/
