### ISSUE TITLE
Patch Weird Title 7 date - "Jan. 30, 2017 (fm)")

### ISSUE THREAD

**Issue by barefootford** [criticaljuncture/ecfr-xml-corrections#154]
From 2017-02-13 to 2017-08-18 Title 7 volume 3 was marked as `Jan. 30, 2017 (fm)`. Date.parse parses correctly, do we still want to fix this?

**Comment by peregrinator** [comment]
https://criticaljuncture.basecamphq.com/projects/4648449-federal-register-2-0/posts/new?return_to=%2Fprojects%2F4648449-federal-register-2-0%2Fposts%2F109219561%2Fcomments

**Comment by barefootford** [comment]
This still looks like it needs a response from steve:
https://criticaljuncture.basecamphq.com/projects/4648449-federal-register-2-0/posts/109225609/comments

**Comment by peregrinator** [comment]
I mentioned the basecamp items to him this morning - he's going to work on
them this week. This one in particular is more a curiosity as I don't think
it's actually breaking any thing...
