### ISSUE TITLE
Determine what to do with Volume 2 ammdate of Title 20 received_on 2017-01-25

### ISSUE THREAD

**Issue by barefootford** [criticaljuncture/ecfr-xml-corrections#155]
Volume 2 for Title 20 had it's amendment date change from January 18, 2017 to December 19 2016 (reverse amendment date). Volume 3 and 4 also changed, but in the next title versions returned to their previous amendment date. I've patched volumes 3 and 4 but haven't been able to determine what happened with volume 2. In its next title version it increases to January 25, 2017 so we'll need to find out what this amendment date, volume 2, should be fore 2017-01-25. 

<img width="619" alt="Screen Shot 2019-09-23 at 11 31 22 AM" src="https://user-images.githubusercontent.com/3782822/65452437-1ecdae00-ddf6-11e9-95fd-79952487f96d.png">

**Comment by peregrinator** [comment]
I did some diffs on the changes from 2017-01-07 through 2017-01-27 and it looks like the 2017-01-25 update was a reversion to the 2017-01-07 update. Based on the FR references in the changes the reversion looks to have been a mistake.

The diff from 2017-01-25 to 2017-01-07 only contains whitespace so I think that update can be safely ignored. So let's
- [ ] remove the patch for volumes 3 & 4
- [ ] delete the '2017-01-25' title version and all it's artifacts
