### ISSUE TITLE
Patch Title 40 § 89.505 to § 89.507 starting on 2019-10-01

### ISSUE THREAD

**Issue by peregrinator** [criticaljuncture/ecfr-xml-corrections#156]
See https://criticaljuncture.basecamphq.com/projects/4648449-federal-register-2-0/posts/109219561/comments

Steve found that some `<SUBJECT>` tags in 89.505 and 89.506 were not closed properly causing these 3 sections to be malformed. He's submitted an update on 2019-10-08 to fix the issue. Once it's available tomorrow we should create a patch that does the same thing for title versions we received starting on 2019-10-01.

**Comment by barefootford** [comment]
Do a diff of today and yesterday, ensure content didn't change, then should be able to migrate todays xml to be ysesterdays

**Comment by barefootford** [comment]
It looks like this has been fixed and merged into master:
https://github.com/criticaljuncture/ecfr-xml-corrections/commit/6406fa2711e8e483ea02fbf6463d3dce2ed1fa5c
