### ISSUE TITLE
Patch 9 CFR 318.12 - remove duplicate

### ISSUE THREAD

**Issue by peregrinator** [criticaljuncture/ecfr-xml-corrections#157]
The duplicate here contains just a HEAD tag so should be easy enough to patch.

https://criticaljuncture.basecamphq.com/projects/4648449-federal-register-2-0/posts/109281217/comments

**Comment by barefootford** [comment]
Looks like this is patched here https://github.com/criticaljuncture/ecfr-xml-corrections/commit/983ea8235edf2c874990ed8d4a80a80f6a3717bf but is still present in pre-processed xml and still needs a reprocessing.
