### ISSUE TITLE
Determine and remove duplicate sections in Title 47 Part 54

### ISSUE THREAD

**Issue by barefootford** [criticaljuncture/ecfr-xml-corrections#161]
Part 54 Subpart G is messed up after an update. It seems Subpart G basically should have been replaced, but instead some old sections were left behind, it's subpart G wrapper tag was removed and there is new/old content mixed in. 

### Fr Doc:
https://www.federalregister.gov/documents/2019/10/11/2019-20173/promoting-telehealth-in-rural-america#sectno-reference-54.623%20

Applicable sections: `54.600 .. 54.633`

This is still broken in the latest Title 47 received on `2019-11-16`. This initially broke on `2019-11-13`.

Not every section has been duplicated.

### Duplicates:
54.600
54.601
54.602
54.603
54.604
54.605
54.607
54.609
54.613
54.615
54.619
54.623
54.625
54.630
54.631
54.632
54.633

**Comment by peregrinator** [comment]
https://criticaljuncture.basecamphq.com/projects/4648449-federal-register-2-0/posts/109485575/comments

**Comment by barefootford** [comment]
This looks to still be broke for title version 47 received_on `2019-12-02`
