### ISSUE TITLE
Title 42 - Part 37 has subparts that do not have identifiers

### ISSUE THREAD

**Issue by barefootford** [criticaljuncture/ecfr-xml-corrections#21]
Title 42 - Part 37 has a number of subparts that don't have identifiers but do have descriptions and sections.
```
Subpart - Chest Radiographic Examinations
Subpart - Spirometry Testing
Subpart - General Requirements
Subpart - Autopsies
```
<img width="246" alt="screen shot 2018-04-11 at 10 17 52 am" src="https://user-images.githubusercontent.com/3782822/38633430-7c6fe880-3d74-11e8-948e-044399ba8de3.png">
PDF: https://www.gpo.gov/fdsys/pkg/CFR-2016-title42-vol1/pdf/CFR-2016-title42-vol1-part37.pdf

new eCFR: https://ecfr.criticaljuncture.org/current/title-42/chapter-I/subchapter-C/part-37?toc=1

**Comment by peregrinator** [comment]
Ok the strategy we determined here is to update the `-web` url generation and canonical redirect to not add subparts that have a blank identifier. This means we won't end up with urls that contain `.../part-37/subpart-/section-37.43` and the content should render correction with a reasonable url

**Comment by barefootford** [comment]
Going to fix through `-web`
https://github.com/criticaljuncture/ecfr-web/issues/243
