### ISSUE TITLE
Future Amendment Date for Title 34 Volume 1 Year 2020

### ISSUE THREAD

**Issue by barefootford** [criticaljuncture/ecfr-xml-corrections#266]
Title 34 `14411` received_on 2020-05-20T20:00:05-0400 had an updated future amendment date of May 22, 2020. Two days later than the received_on date.

This persists through 2020-06-19T20:00:10-0400.xml when it becomes June 25, 2020.

```
Vol1 Amendment date: May 22, 2020
14411	34	2020-05-21 00:00:05	NULL	2020-05-20T20:00:05-0400.xml
14428	34	2020-05-23 00:30:13	NULL	2020-05-22T20:30:13-0400.xml
14636	34	2020-06-12 01:00:34	NULL	2020-06-11T21:00:34-0400.xml
14674	34	2020-06-19 02:30:13	NULL	2020-06-18T22:30:13-0400.xml
14683	34	2020-06-20 00:00:10	NULL	2020-06-19T20:00:10-0400.xml

Vol1 Amendment date: June 25, 2020
14721	34	2020-06-27 03:30:09	NULL	2020-06-26T23:30:09-0400.xml

```

The diff between Title 34 received_on 2020-05-20 and the previous title_version received_on 2020-03-05 is just a bunch of cross references for some laws that will become effective in August 2020.

Referenced Fr doc was published on May 19, 2020 and becomes effective
August 14, 2020
https://www.federalregister.gov/documents/2020/05/19/2020-10512/nondiscrimination-on-the-basis-of-sex-in-education-programs-or-activities-receiving-federal

**Comment by peregrinator** [comment]
Patch looks to have been properly created. The amendment date changed in accordance with the OFR rules about adding cross references but the editor just chose the wrong date for the amendment date.
