### ISSUE TITLE
Investigate subject groups in 17 CFR 240

### ISSUE THREAD

**Issue by andrewcarpenter** [criticaljuncture/ecfr-xml-corrections#329]
eg here https://www.ecfr.gov/current/title-17/chapter-II/part-240/subject-group-ECFRfd272fe04b7d4e6

vs https://www.ecfr.gov/current/title-17/chapter-II/part-240#240.14a-1

**Comment by raybaxter** [comment]
Resolved in https://github.com/criticaljuncture/ecfr-versioner/issues/908
