### ISSUE TITLE
Fix duplicate/broken Title 5 - Chapter CI tag

### ISSUE THREAD

**Issue by barefootford** [criticaljuncture/ecfr-xml-corrections#42]
We'll want to remove the empty one and set CI on the DIV3 that has content inside it. We'll need to see if this is currently fixed and then set the patch date range appropriately.
- [ ] Check Date range
- [ ] Create Patch

<hr/>
Title 5 has a Chapter Typo in the XML that is causing processing issues when generating structure Json.
We should notify OFR to fix future xml and then probably patch this so processing can succeed.

```xml
<DIV3 N="CI" TYPE="CHAPTER">
  <HEAD> CHAPTER CI - NATIONAL MEDIATION BOARD</HEAD>
</DIV3>
<DIV3 N="" TYPE="CHAPTER">
  <HED>CHAPTER CI - NATIONAL MEDIATION BOARD </HED>
  <DIV5 N="10101" TYPE="PART">
    <HEAD>PART 10101 - SUPPLEMENTAL STANDARDS OF ETHICAL CONDUCT FOR EMPLOYEES OF THE NATIONAL MEDIATION BOARD </HEAD>
    <AUTH>
```

Honeybadger:
https://app.honeybadger.io/projects/51157/faults/38461198#notice-trace

**Comment by peregrinator** [comment]
@barefootford do we know what date this appeared on?

**Comment by barefootford** [comment]
No, but I can look real quick. It seems like CI is a newish chapter

**Comment by barefootford** [comment]
It looks like title_version 5 that was received on 2018-11-03 with an amended on of 2018-11-01 is the first insertion of Chapter CI.

Title Version id `7543`
