### ISSUE TITLE
Patch Titles with appendices whose identifiers are "Appendix to"

### ISSUE THREAD

**Issue by barefootford** [criticaljuncture/ecfr-xml-corrections#43]
There are about 30 titles using an older appendix format where instead of giving appendices identifiers the appendix format is "Appendix to Part 50 - Description about this appendix"

We currently process these labels as having an identifier of "Appendix to". We'll need to patch these appendices to have identifiers in order for processing to work. 

The number of titles using this format has been reduced recently, but we'll still need to patch this older format.

```
irb(main):012:0> ContentVersion.where(section_identifier: 'Appendix to').select(:title).map(&:title).size
ContentVersion Load (84.9ms)  SELECT `content_versions`.`title` FROM `content_versions` WHERE `content_versions`.`section_identifier` = 'Appendix to'
=> 2600

ContentVersion.where(section_identifier: 'Appendix to').where('received_on > ?', 2.months.ago).select(:title).map(&:title).size
ContentVersion Load (107.0ms)  SELECT `content_versions`.`title` FROM `content_versions` WHERE `content_versions`.`section_identifier` = 'Appendix to' AND (received_on > '2018-09-08 18:45:35.051483')
=> 582
```

**Comment by peregrinator** [comment]
We moved this work into a preprocessor in -versioner.
