### ISSUE TITLE
30 CFR 779.25 has duplicate sections after section was nullified

### ISSUE THREAD

**Issue by barefootford** [criticaljuncture/ecfr-xml-corrections#49]
It looks like there were multiple parts in Title 30 Parts 700-827 that were nullified. 30 CFR 779.25 appears to show the old content and then also has a reserved tag placed for the same content. This is causing churn on this section as we're seeing new content and then that content changing to reserved on each import. 

<img width="992" alt="screen shot 2019-01-08 at 11 13 41 am" src="https://user-images.githubusercontent.com/3782822/50853217-83171300-1336-11e9-9d3d-96aceccd24f8.png">

https://ecfr.criticaljuncture.org/current/title-30/chapter-VII/subchapter-G/part-779/section-779.25

This is present in the XML as well as in print.
### PDF
<img width="286" alt="screen shot 2019-01-08 at 10 46 54 am" src="https://user-images.githubusercontent.com/3782822/50853093-24519980-1336-11e9-815e-8ac6c2c9f3af.png">
<img width="258" alt="screen shot 2019-01-08 at 10 46 59 am" src="https://user-images.githubusercontent.com/3782822/50853098-27e52080-1336-11e9-8b9d-122b3060fc69.png">

https://www.govinfo.gov/content/pkg/CFR-2018-title30-vol3/pdf/CFR-2018-title30-vol3-part779.pdf

### XML
```
<DIV8 N="§ 779.25" TYPE="SECTION">
<HEAD>§ 779.25   Cross sections, maps, and plans.</HEAD>
<P>(a) The application shall include cross sections, maps, and plans showing - 
</P>
<P>(1) Elevations and locations of test borings and core samplings;
</P>
<P>(2) Elevations and locations of monitoring stations used to gather data for water quality and quantity, fish and wildlife, and air quality, if required, in preparation of the application;
</P>
...
</DIV8>

<DIV8 N="§ 779.25" TYPE="SECTION">
<HEAD>§ 779.25   [Reserved]</HEAD>
</DIV8>
```

FR Doc:
https://www.federalregister.gov/documents/2017/11/17/2017-24307/congressional-nullification-of-the-stream-protection-rule-under-the-congressional-review-act

**Comment by peregrinator** [comment]
After reviewing the FR docs here, [original rule],(https://www.federalregister.gov/documents/2016/12/20/2016-29958/stream-protection-rule) and here, [revocation](https://www.federalregister.gov/documents/2017/11/17/2017-24307/congressional-nullification-of-the-stream-protection-rule-under-the-congressional-review-act), we need to create a patch to remove the second of the duplicates (the one marked reserved). This patch should run from 2017-11-21 to 2018-10-02 (it was fixed on 2018-10-29).
