### ISSUE TITLE
7 CFR 1773 has all of it's subparts and sections duplicated

### ISSUE THREAD

**Issue by barefootford** [criticaljuncture/ecfr-xml-corrections#51]
Title 7 Part 1773 has all of it's Subparts (and child sections) duplicated in the most recent Title 7 XML.
`Subpart A, Subpart B, Subpart C, Subpart D, Subpart E`

TOC view:
https://ecfr.criticaljuncture.org/on/2019-02-12/title-7/subtitle-B/chapter-XVII/part-1773?toc=1
This is confirmed by looking at the source xml.

These look similar but not identical. It appears the top subparts may be newer because they include an active `§ 1773.49 OMB Control Number` where as the second set has 1773.49 set to reserved.

<img width="651" alt="screen shot 2019-01-09 at 1 23 14 pm" src="https://user-images.githubusercontent.com/3782822/50929482-2721bc80-1412-11e9-973e-d4f83e818d6f.png">

This is only in the xml and does not show up in print. 

PDF:
https://www.govinfo.gov/content/pkg/CFR-2018-title7-vol12/pdf/CFR-2018-title7-vol12-part1773.pdf

I think the most recent change to this part was in 2014, but I'm not sure if this is when the error was introduced:
https://www.federalregister.gov/documents/2014/12/19/2014-28697/federal-awarding-agency-regulatory-implementation-of-office-of-management-and-budgets-uniform

**Comment by peregrinator** [comment]
OFR updated this to remove the duplicates in 2019. We're now able to fix as a patch
