### ISSUE TITLE
Title 15 Part 2004 initially inserted without part identifier

### ISSUE THREAD

**Issue by barefootford** [criticaljuncture/ecfr-xml-corrections#54]
Title 15 Part 2004 was initially inserted 2016-12-13 without an identifier
This is fixed and updated in the latest xml.

```xml
  <DIV5 N="" TYPE="PART">
    <HEAD>DISCLOSURE OF RECORDS AND INFORMATION</HEAD>
    <SOURCE>
      <HED>Source:</HED><PSPACE>81 FR 89846, Dec. 13, 2016, unless otherwise noted.</PSPACE>
    </SOURCE>

    <DIV6 N="A" TYPE="SUBPART">
    <HEAD>Subpart A - Definitions</HEAD>
    ...
```

This made it into the 2017 print PDF without the identifier:
https://www.govinfo.gov/content/pkg/CFR-2017-title15-vol3/pdf/CFR-2017-title15-vol3-part2003.pdf

Originating FR Doc:
https://www.federalregister.gov/documents/2016/12/13/2016-29875/production-or-disclosure-of-records-information-and-employee-testimony-in-legal-proceedings

<hr/>

This is fixed in the 2018 print volume through an FR update on 2017-09-29, updated to include the identifier 2004 but without updating the amendment date.
https://www.govinfo.gov/content/pkg/CFR-2018-title15-vol3/pdf/CFR-2018-title15-vol3-part2004.pdf

<hr/>

Do we want to patch this to always include 2004 as the identifier or do we want to create a generated/hidden identifier which will change the history so Part 2004 begins in 2018?

<hr/>

<img width="349" alt="screen shot 2019-01-29 at 5 00 58 pm" src="https://user-images.githubusercontent.com/3782822/51951006-a1c57280-23e7-11e9-917f-76e406b4d7bb.png">
<hr/>
<img width="389" alt="screen shot 2019-01-29 at 5 01 48 pm" src="https://user-images.githubusercontent.com/3782822/51951005-a1c57280-23e7-11e9-8ce5-c665c04cb6b3.png">
<hr/>
<img width="851" alt="screen shot 2019-01-29 at 4 56 12 pm" src="https://user-images.githubusercontent.com/3782822/51951007-a1c57280-23e7-11e9-8eaa-e416b8b342e9.png">

<hr/>

**Comment by peregrinator** [comment]
Basecamp discussion here: https://criticaljuncture.basecamphq.com/projects/4648449-federal-register-2-0/posts/108273945/comments

**Comment by peregrinator** [comment]
Steve would like us to create a patch that adds in the correct identifier for the part - but leaving the `<HEAD>` text as is.

**Comment by barefootford** [comment]
works for me 👍
