### ISSUE TITLE
Patch Title 33 Amendment Date

### ISSUE THREAD

**Issue by barefootford** [criticaljuncture/ecfr-xml-corrections#72]
I think we're already aware of this, but for tracking purposes...

Title 33 has a broken amendment date that is still present in the latest XML (2019-02-08)

- [ ]  Patch top amendment date from 2019-02-02 to current

```
<AMDDATE>Dec. 24, 26, 2018
</AMDDATE>

<DIV1 N="1" TYPE="TITLE">

<HEAD>Title 33 - Navigation and Navigable Waters--Volume 1</HEAD>
```

**Comment by peregrinator** [comment]
Steve says the correct date is Dec. 26 so we can create a correction for this!
