### ISSUE TITLE
Add a patch for Title 31, Subpart A that removes the extraneous chapter

### ISSUE THREAD

**Issue by peregrinator** [criticaljuncture/ecfr-xml-corrections#8]
It appears the the GPO DTD requires that there be a chapter and they are inserting a `Chapter I` that is blank in `Subtitle A`. There is a `Chapter I` in this title but it occurs under `Subtitle B` (all chapters in this title live here).

- [x] Add a patch that removes the extraneous chapter (the `<DIV3>` below) and its closing tag at the end of this subtitle.

```xml
    ...
    <DIV2 N="Subtitle A" TYPE="SUBTITLE">
      <HEAD>Subtitle A - Office of the Secretary of the Treasury </HEAD>
      <DIV3 N="I" TYPE="CHAPTER">
        <DIV5 N="0" TYPE="PART">
          <HEAD>PART 0 - DEPARTMENT OF THE TREASURY EMPLOYEE RULES OF CONDUCT </HEAD>
    ...
```

**Comment by barefootford** [comment]
~~-[X] Fix identifiers with subtitle inside `N`~~

~~@peregrinator I assume we'll also want a patch for all the weird n identifers?~~
Correction: Looks like we strip subtitles from identifiers when we create structure json

```
<DIV2 N="Subtitle A" TYPE="SUBTITLE"> =>
<DIV2 N="A" ... >
```
