### ISSUE TITLE
Title 37 Handle subchapter without identifier

### ISSUE THREAD

**Issue by peregrinator** [criticaljuncture/ecfr-xml-corrections#9]
Not sure why the GPO parsers handles this title this way but the Title is a bit abnormal.

It looks like they've moved the parts out of order so that they could group them by content categories. This results in a second subchapter tag that wrapping content that should be in subchapter A.

I think the correct fix here would be to add a patch that corrects the second subchapter by adding in the correct information such that we then combine these subchapters together in our later preprocessing steps. The order of the parts would then be maintained.

The GPO site has an issue here where they label it 'Unknown Title', https://www.gpo.gov/fdsys/browse/collectionCfr.action?collectionCode=CFR&searchPath=Title+37%2FChapter+I%2FSubchap&oldPath=Title+37%2FChapter+I&isCollapsed=true&selectedYearFrom=2017&ycord=1127

But the PDF clearly shows this as part of subchapter A, https://www.gpo.gov/fdsys/pkg/CFR-2017-title37-vol1/pdf/CFR-2017-title37-vol1-chapI.pdf

**Comment by barefootford** [comment]
- [ ] We'd like to patch both of these nested subchapter identifiers to also be subchapter A, then rely on the `VolumeConsolidator` preprocessor step to collapse them.

Right now the `VolumeConsolidator` skips the work if it doesn't find more than one title, it may be as simple as turning off that step and always having it collapse collapsible nodes. Will have to  make the patch, then pry into versioner and see if that will work.

**Comment by peregrinator** [comment]
So while our preference is to always leave the XML as close as possible to what we get from GPO it seems like we may just need to go ahead and use a patch to wrap these into a single subchapter.

In this case if we need to end up modifying the volume consolidator then let's just go with the patch route unless we find this happening in more than a couple places :/
